//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ModuleReaderManager.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MODULEREADERMANAGER_DIALOG  102
#define IDD_CUSTOMDLG_DIALOG            104
#define IDD_ISO180006BOPDLG_DIALOG      105
#define IDD_TESTGPIODLG_DIALOG          106
#define IDD_OTHERPARAMS_DIALOG          107
#define IDD_ARM7_16ANTSETDLG_DIALOG     108
#define IDR_MAINFRAME                   128
#define IDC_tbsrcstr                    1000
#define IDC_btnconnect                  1001
#define IDC_LIST1                       1002
#define IDC_btnconnect2                 1002
#define IDC_btndisconnect               1002
#define IDC_btnstart                    1003
#define IDC_btnstop                     1004
#define IDC_btnclear                    1005
#define IDC_tbfbank                     1006
#define IDC_tbfaddr                     1007
#define IDC_tbfdata                     1008
#define IDC_tbaccesspwd                 1009
#define IDC_ccpwd                       1011
#define IDC_ccfilter                    1012
#define IDC_tbbank                      1013
#define IDC_tbaddr                      1014
#define IDC_tbblocks                    1015
#define IDC_data                        1016
#define IDC_tbdata                      1017
#define IDC_btnread                     1018
#define IDC_btnwrite                    1019
#define IDC_btnlock                     1020
#define IDC_btnkill                     1021
#define IDC_tblockobj                   1022
#define IDC_tblocktype                  1023
#define IDC_ccInvert                    1024
#define IDC_ccant1                      1025
#define IDC_ccant2                      1026
#define IDC_ccant3                      1027
#define IDC_ccant4                      1028
#define IDC_COMBO1                      1030
#define IDC_readertype                  1030
#define IDC_cbchkant                    1030
#define IDC_fiterbank                   1031
#define IDC_SelectRegion                1031
#define IDC_lockobj                     1033
#define IDC_wrbank                      1035
#define IDC_wrdata                      1036
#define IDC_locktype                    1038
#define IDC_repcnt                      1039
#define IDC_redloginfo                  1040
#define IDC_repsirand                   1041
#define IDC_reprandlen                  1042
#define IDC_repisrep                    1043
#define IDC_timeout                     1044
#define IDC_btnstoptest                 1045
#define IDC_EDIT1                       1046
#define IDC_tbebstartaddr               1046
#define IDC_editpwd                     1046
#define IDC_tbstaddr                    1046
#define IDC_EDITqval                    1046
#define IDC_tbreadpwr                   1046
#define IDC_etsend                      1046
#define IDC_COMBO2                      1047
#define IDC_cbbytes                     1047
#define IDC_tbblks                      1047
#define IDC_cbuniant                    1047
#define IDC_etrecv                      1047
#define IDC_COMBO3                      1048
#define IDC_cbaddbank                   1048
#define IDC_cbuniemd                    1048
#define IDC_cmbpsam                     1048
#define IDC_CHECK1                      1049
#define IDC_ckisaddtiondata             1049
#define IDC_blkck1                      1049
#define IDC_ckant1                      1049
#define IDC_ckgpi1                      1049
#define IDC_cbrechrssi                  1049
#define IDC_EDIT2                       1050
#define IDC_tbant1rp                    1050
#define IDC_blkck2                      1050
#define IDC_ckgpo1                      1050
#define IDC_EDITfbank                   1050
#define IDC_writepwr                    1050
#define IDC_EDIT3                       1051
#define IDC_tbant2rp                    1051
#define IDC_blkck3                      1051
#define IDC_EDITfbitstart               1051
#define IDC_EDIT4                       1052
#define IDC_tbant3rp                    1052
#define IDC_blkck4                      1052
#define IDC_EDITfbitlen                 1052
#define IDC_tbgen2blf                   1052
#define IDC_EDIT5                       1053
#define IDC_tbant4rp                    1053
#define IDC_blkck5                      1053
#define IDC_EDITfmdata                  1053
#define IDC_ckant5                      1053
#define IDC_EDIT6                       1054
#define IDC_tbant1wp                    1054
#define IDC_blkck6                      1054
#define IDC_EDITebank                   1054
#define IDC_ckant6                      1054
#define IDC_EDIT7                       1055
#define IDC_tbant2wp                    1055
#define IDC_blkck7                      1055
#define IDC_EDITestart                  1055
#define IDC_ckant7                      1055
#define IDC_EDIT8                       1056
#define IDC_tbant3wp                    1056
#define IDC_blkck8                      1056
#define IDC_EDITmbytescnt               1056
#define IDC_ckant8                      1056
#define IDC_EDIT9                       1057
#define IDC_tbant4wp                    1057
#define IDC_EDITmpwd                    1057
#define IDC_ckant9                      1057
#define IDC_ckperm1                     1057
#define IDC_EDIT10                      1058
#define IDC_tbip                        1058
#define IDC_EDITmval                    1058
#define IDC_ckant13                     1058
#define IDC_ckperm2                     1058
#define IDC_tbsrbank                    1058
#define IDC_EDIT11                      1059
#define IDC_tbgateway                   1059
#define IDC_EDITfmatch                  1059
#define IDC_ckant14                     1059
#define IDC_ckperm3                     1059
#define IDC_EDIT12                      1060
#define IDC_tbsubnet                    1060
#define IDC_ckant15                     1060
#define IDC_cbgen2tari                  1060
#define IDC_ckperm4                     1060
#define IDC_BUTTON1                     1061
#define IDC_btnsetconf                  1061
#define IDC_btnChangeEAS                1061
#define IDC_btngetgpi                   1061
#define IDC_btnsetqval                  1061
#define IDC_ckant16                     1061
#define IDC_BUTTON2                     1062
#define IDC_btngetconf                  1062
#define IDC_btnEASAlarm                 1062
#define IDC_btnsetgpo                   1062
#define IDC_btngetqval                  1062
#define IDC_btnok                       1062
#define IDC_COMBO4                      1063
#define IDC_cbsess                      1063
#define IDC_btnsetmval                  1063
#define IDC_ckperm5                     1063
#define IDC_btnCustomCmd                1064
#define IDC_btngetmval                  1064
#define IDC_ckperm6                     1064
#define IDC_rdset                       1065
#define IDC_btnsetmaxepc                1065
#define IDC_btnsetchk                   1065
#define IDC_rdreset                     1066
#define IDC_btngetchk                   1066
#define IDC_rdant1                      1067
#define IDC_setRegion                   1067
#define IDC_rdant2                      1068
#define IDC_getRegion                   1068
#define IDC_rdant3                      1069
#define IDC_btngethtb                   1069
#define IDC_rdant4                      1070
#define IDC_btnsethtb                   1070
#define IDC_statEASData                 1071
#define IDC_cbgen2target                1071
#define IDC_BUTTON3                     1072
#define IDC_btnBlockReadLock            1072
#define IDC_btnwriteepc                 1072
#define IDC_btnsetfilter                1072
#define IDC_btnset                      1072
#define IDC_btnexec                     1072
#define IDC_btngetfilter                1073
#define IDC_btnsetemb                   1074
#define IDC_ckperm7                     1074
#define IDC_cbmaxepc                    1075
#define IDC_btngetemb                   1075
#define IDC_ckperm8                     1075
#define IDC_CKGEN2                      1076
#define IDC_btnresetfilter              1076
#define IDC_CKISO180006B                1077
#define IDC_btnresetemb                 1077
#define IDC_btn180006bop                1078
#define IDC_cblbtenable                 1078
#define IDC_ckant2                      1079
#define IDC_btntestgpio                 1079
#define IDC_tbsraddress                 1079
#define IDC_ckant3                      1080
#define IDC_ckant4                      1081
#define IDC_rtbdata                     1082
#define IDC_ckant10                     1082
#define IDC_ckant11                     1083
#define IDC_listtag                     1084
#define IDC_ckant12                     1084
#define IDC_ckgpi2                      1086
#define IDC_ckgpi3                      1087
#define IDC_ckgpi4                      1088
#define IDC_ckgpo2                      1089
#define IDC_ckgpo3                      1090
#define IDC_ckgpo4                      1091
#define IDC_btnotherparam               1101
#define IDC_listhtb                     1106
#define IDC_STATIC_boardtype            1107
#define IDC_STATIC_moduletype           1108
#define IDC_CKIPX64                     1109
#define IDC_CKIPX256                    1110
#define IDC_btnsetgen2blf               1111
#define IDC_btngetgen2blf               1112
#define IDC_tbreaddur                   1112
#define IDC_tbsleepdur                  1113
#define IDC_btnuniantget                1113
#define IDC_listtags                    1114
#define IDC_btnuniantset                1114
#define IDC_btnuniemdget                1115
#define IDC_tbemdbytes                  1116
#define IDC_btnuniemdset                1116
#define IDC_btnrechrssiget              1117
#define IDC_btnrechrssiset              1118
#define IDC_btn16antsset                1119
#define IDC_btngen2tariget              1119
#define IDC_btngen2tariset              1120
#define IDC_btngen2targetget            1121
#define IDC_btngen2targetset            1122
#define IDC_btnhoptimeget               1123
#define IDC_btnrandrw                   1124
#define IDC_btnhoptimeset               1124
#define IDC_btnclearlog                 1125
#define IDC_btnlbtenbleget              1125
#define IDC_rbimpinjqtcmdtread          1126
#define IDC_btnlbtenbleset              1126
#define IDC_rbimpinjqtcmdtwrite         1127
#define IDC_btngen2wmodeget             1127
#define IDC_rbimpinjqtmemtpublic        1128
#define IDC_btngen2wmodeset             1128
#define IDC_rbimpinjqtmemtprivate       1129
#define IDC_btn6bblfget                 1129
#define IDC_rbimpinjqtrangetnear        1130
#define IDC_btn6bblfset                 1130
#define IDC_rbimpinjqtrangetfar         1131
#define IDC_btnsetinvmode               1131
#define IDC_rbimpinjqtpersistperm       1132
#define IDC_btngetinvmode               1132
#define IDC_rbimpinjqtpersisttemp       1133
#define IDC_btnsetimpinjqt              1134
#define IDC_tbhoptime                   1137
#define IDC_cbgen2wmode                 1139
#define IDC_cbgen2enc                   1141
#define IDC_tb6bblf                     1142
#define IDC_tbstartblk                  1143
#define IDC_tbblkrange                  1144
#define IDC_btnpermlockget              1145
#define IDC_btnpermlockset              1146
#define IDC_cbpwdtype                   1146
#define IDC_cbtagtype                   1147
#define IDC_tbsrblks                    1148
#define IDC_tbindexbitnum               1149
#define IDC_tbindexbitaddr              1150
#define IDC_tbsracspwd                  1151
#define IDC_btngetsecureread            1152
#define IDC_btnsetsecureread            1153
#define IDC_btnflashwrite               1154
#define IDC_tbflashwrtieaddr            1155
#define IDC_tbflashwrtiedata            1156
#define IDC_btnresetsr                  1157
#define IDC_BUTTON5                     1159
#define IDC_BUTTON_savesettings         1159
#define IDC_cbtransmitmode              1161
#define IDC_btngettransmitmod           1162
#define IDC_btnsettransmitmod2          1163
#define IDC_cbpowersave                 1164
#define IDC_btngetpowersavemode         1165
#define IDC_BUTTON4                     1165
#define IDC_btnsetpowersavemode         1166
#define IDC_BUTTON6                     1166
#define IDC_BUTTON7                     1167
#define IDC_BUTTON_eraseconf            1167
#define IDC_Chkasyncread                1168
#define IDC_Cbbinvmode                  1169
#define IDC_rdpsam1                     1170

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1172
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
